version: '3.8'

services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.cuda
    networks:
      - cluster
    volumes:
      - media:/media

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - cluster

  proxy:
    build: ./proxy
    ports:
      - 80:80
    networks:
      - cluster
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server
      - frontend

networks:
  cluster:

volumes:
  media: