services:

  server:
    build: ./server
    networks:
      - cluster
    volumes:
      - ./server:/app/server
      - media:/media

  frontend:
    build: ./frontend
    networks:
      - cluster
    volumes:
      - ./frontend:/app/frontend

  proxy:
    build: ./proxy
    ports:
      - 80:80
    networks:
      - cluster
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server
      - frontend

networks:
  cluster:

volumes:
  media: