services:

  server:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    networks:
      - cluster
    volumes:
      - media:/media
      - data:/data
    command: uv run uvicorn --host 0.0.0.0 --port 80 --reload app:app
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app/api
          ignore:
            - .venv/
        - action: rebuild
          path: ./api/pyproject.toml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - cluster
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  proxy:
    build: ./proxy
    ports:
      - 80:80
    networks:
      - cluster
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server
      - frontend

networks:
  cluster:

volumes:
  media:
  data: